openapi: 3.0.3
info:
  title: MiniReipaz API
  version: 1.0.0
  description: API for managing workflows and users.

servers:
  - url: https://localhost:4020/api
    description: Local server

security:
  - BearerAuth: []

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    CreateWorkflowRequest:
      type: object
      properties:
        sub:
          type: string
          pattern: '^\d+$'  # Solo números
          maxLength: 50
          example: "123123123123123123"
        workflowname:
          type: string
          pattern: '^[a-zA-Z0-9 ]+$'
          maxLength: 255
          example: "Example Workflow"
        directorytosave:
          type: string
          pattern: '^[a-zA-Z0-9 ]+$'
          maxLength: 255
          example: "/path/to/save"
      required:
        - sub
        - workflowname
        - directorytosave
      additionalProperties: false

    Workflow:
      type: object
      properties:
        sub:
          type: string
          pattern: '^\d+$'  # Solo números
          maxLength: 50
          example: "123123123123123123"
        uuid:
          type: string
          format: uuid
          pattern: '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$'
          maxLength: 40
          example: "550e8400-e29b-41d4-a716-446655440000"
        workflowname:
          type: string
          pattern: '^[a-zA-Z0-9 ]+$'
          maxLength: 255
          example: "Example Workflow"
        directorytosave:
          type: string
          pattern: '^[a-zA-Z0-9 ]+$'
          maxLength: 255
          example: "/path/to/save"
        createdat:
          type: string
          format: date-time
          maxLength: 30
          example: "2023-01-01T10:00:00Z"
        updatedat:
          type: string
          format: date-time
          maxLength: 30
          example: "2023-06-01T10:00:00Z"
      additionalProperties: false

    SyncUserRequest:
      type: object
      properties:
        sub:
          type: string
          pattern: '^\d+$'  # Solo números
          maxLength: 50
          example: "123123123123123123"
        access_token:
          type: string
          pattern: '^[A-Za-z0-9._-]+$'
          maxLength: 1000
          example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
        status:
          type: string
          enum:
            - active
            - invited
            - pending
            - blocked
        roleId:
          type: string
          enum:
            - admin
            - user
            - moderator
            - editor
            - guest
            - customer
            - support
            - manager
            - analyst
            - developer
      required:
        - sub
      additionalProperties: false

    SyncUserResponse:
      type: object
      additionalProperties: false
      properties:
        error:
          type: string
          maxLength: 255
          pattern: '^[a-zA-Z0-9 ]+$'
          example: ""
        status:
          type: integer
          example: 200
        exist:
          type: boolean
          example: true
        created:
          type: boolean
          example: false

    UnauthorizedError:
      type: object
      additionalProperties: false
      properties:
        error:
          type: string
          pattern: '^[A-Za-z0-9_ ]+$'  # Ajusta el patrón según tus necesidades
          maxLength: 255
          example: "Authorization header is required"

    InvalidRequestError:
      type: object
      additionalProperties: false
      properties:
        error:
          type: string
          pattern: '^[A-Za-z0-9_ ]+$'  # Ajusta el patrón según tus necesidades
          maxLength: 255
          example: "Invalid request format"

    UnsupportedMediaTypeError:
      type: object
      additionalProperties: false
      properties:
        error:
          type: string
          pattern: '^[A-Za-z0-9_ ]+$'  # Ajusta el patrón según tus necesidades
          maxLength: 255
          example: "Unsupported media type"

    TooManyRequestsError:
      type: object
      additionalProperties: false
      properties:
        error:
          type: string
          pattern: '^[A-Za-z0-9_ ]+$'  # Ajusta el patrón según tus necesidades
          maxLength: 255
          example: "Too many requests"

  responses:
    UnauthorizedError:
      description: Unauthorized request due to missing or invalid token
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UnauthorizedError'

    InvalidRequestError:
      description: The request format is invalid
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/InvalidRequestError'

    UnsupportedMediaTypeError:
      description: The request media type is not supported
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UnsupportedMediaTypeError'

    TooManyRequestsError:
      description: The client has sent too many requests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/TooManyRequestsError'

paths:
  /ping:
    get:
      summary: Ping to check if the service is running.
      security:
        - BearerAuth: []
      responses:
        '200':
          description: OK, the service is active.
          content:
            application/json:
              schema:
                pattern: '^[a-zA-Z0-9 ]+$'
                maxLength: 255
                type: string
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '406':
          $ref: '#/components/responses/InvalidRequestError'
        '415':
          $ref: '#/components/responses/UnsupportedMediaTypeError'
        '429':
          $ref: '#/components/responses/TooManyRequestsError'
        'default':
          description: Unexpected error.
          content:
            application/json:
              schema:
                type: object
                additionalProperties: false
                properties:
                  error:
                    pattern: '^[a-zA-Z0-9 ]+$'
                    maxLength: 255
                    type: string

  /workflows:
    post:
      summary: Create a new workflow.
      operationId: createWorkflow
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateWorkflowRequest'
      responses:
        '201':
          description: Workflow created successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Workflow'
        '400':
          description: Validation error.
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '415':
          $ref: '#/components/responses/UnsupportedMediaTypeError'
        '429':
          $ref: '#/components/responses/TooManyRequestsError'
        '500':
          description: Internal server error.
        'default':
          description: Unexpected error.
          content:
            application/json:
              schema:
                type: object
                additionalProperties: false
                properties:
                  error:
                    pattern: '^[a-zA-Z0-9 ]+$'
                    maxLength: 255
                    type: string

  /users:
    post:
      summary: Sync user with ID provider.
      operationId: syncUser
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SyncUserRequest'
      responses:
        '200':
          description: User synced successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SyncUserResponse'
        '400':
          description: Validation error.
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '415':
          $ref: '#/components/responses/UnsupportedMediaTypeError'
        '429':
          $ref: '#/components/responses/TooManyRequestsError'
        '500':
          description: Internal server error.
        'default':
          description: Unexpected error.
          content:
            application/json:
              schema:
                type: object
                additionalProperties: false
                properties:
                  error:
                    pattern: '^[a-zA-Z0-9 ]+$'
                    maxLength: 255
                    type: string
