// Code generated by mockery v2.51.1. DO NOT EDIT.

package mocks

import (
	models "minireipaz/pkg/domain/models"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// CredentialBrokerRepository is an autogenerated mock type for the CredentialBrokerRepository type
type CredentialBrokerRepository struct {
	mock.Mock
}

// CreateCredential provides a mock function with given fields: token, refresh, expire, stateInfo
func (_m *CredentialBrokerRepository) CreateCredential(token *string, refresh *string, expire *time.Time, stateInfo *models.RequestExchangeCredential) bool {
	ret := _m.Called(token, refresh, expire, stateInfo)

	if len(ret) == 0 {
		panic("no return value specified for CreateCredential")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(*string, *string, *time.Time, *models.RequestExchangeCredential) bool); ok {
		r0 = rf(token, refresh, expire, stateInfo)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// NewCredentialBrokerRepository creates a new instance of CredentialBrokerRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCredentialBrokerRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CredentialBrokerRepository {
	mock := &CredentialBrokerRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
