// Code generated by mockery v2.51.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// CredentialFacebookHTTPRepository is an autogenerated mock type for the CredentialFacebookHTTPRepository type
type CredentialFacebookHTTPRepository struct {
	mock.Mock
}

// NewCredentialFacebookHTTPRepository creates a new instance of CredentialFacebookHTTPRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCredentialFacebookHTTPRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CredentialFacebookHTTPRepository {
	mock := &CredentialFacebookHTTPRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
